-- MySQL Script generated by MySQL Workbench
-- Tue 14 Jul 2020 09:40:37 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bookstore` ;
USE `Bookstore` ;

-- -----------------------------------------------------
-- Table `Bookstore`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Category` (
  `idCategory` INT NOT NULL,
  `category` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Books` (
  `ISBN` INT NOT NULL,
  `author` VARCHAR(30) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `cover` VARCHAR(30) NOT NULL,
  `edition` VARCHAR(5) NOT NULL,
  `publisher` VARCHAR(30) NOT NULL,
  `pubYear` INT(5) NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Category_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_Category`
    FOREIGN KEY (`category`)
    REFERENCES `Bookstore`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`userType` (
  `idUserType` INT NOT NULL,
  `userStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUserType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Users` (
  `userID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT(10) NULL,
  `userTypeID` INT NOT NULL,
  `Subscription` TINYINT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_userStatus_idx` (`userTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_userTypeID`
    FOREIGN KEY (`userTypeID`)
    REFERENCES `Bookstore`.`userType` (`idUserType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Bookstore`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Address` (
  `idAddress` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `street` VARCHAR(30) NOT NULL,
  `street2` VARCHAR(30) NULL,
  `zipCode` INT(5) NOT NULL,
  `city` VARCHAR(15) NOT NULL,
  `state` VARCHAR(30) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `AddressType` VARCHAR(5) NULL,
  `userID` INT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_userID_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `Bookstore`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Payment` (
  `cardNumber` INT NOT NULL,
  `name` VARCHAR(11) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `securityCode` INT(3) NOT NULL,
  `paymentType` VARCHAR(15) NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`cardNumber`),
  INDEX `fk_userID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_userID`
    FOREIGN KEY (`UserID`)
    REFERENCES `Bookstore`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Promotion` (
  `idPromotion` INT NOT NULL,
  `promoCode` VARCHAR(45) NOT NULL,
  `discountAmount` INT(5) NOT NULL,
  `startDate` DATE NOT NULL,
  `expirationDate` DATE NOT NULL,
  PRIMARY KEY (`idPromotion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Order` (
  `orderID` INT NOT NULL,
  `userID` INT NOT NULL,
  `total` INT NULL,
  `OrderDateTime` DATE NOT NULL,
  `AddressID` INT NOT NULL,
  `PromoID` INT NOT NULL,
  `paymentID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_UserID_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_addressID_idx` (`AddressID` ASC) VISIBLE,
  INDEX `fk_PromoID_idx` (`PromoID` ASC) VISIBLE,
  CONSTRAINT `fk_UserID`
    FOREIGN KEY (`userID`)
    REFERENCES `Bookstore`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addressID`
    FOREIGN KEY (`AddressID`)
    REFERENCES `Bookstore`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PromoID`
    FOREIGN KEY (`PromoID`)
    REFERENCES `Bookstore`.`Promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`Cart` (
  `idCart` INT NOT NULL,
  `userID` INT NOT NULL,
  `orderID` INT NOT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `fk_userID_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_orderID_idx` (`orderID` ASC) VISIBLE,
  CONSTRAINT `fk_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `Bookstore`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderID`
    FOREIGN KEY (`orderID`)
    REFERENCES `Bookstore`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`cartItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`cartItems` (
  `idcartItems` INT NOT NULL,
  `cartID` INT NOT NULL,
  `bookID` INT NOT NULL,
  `quantity` INT(10) NOT NULL,
  PRIMARY KEY (`idcartItems`),
  INDEX `fk_cartID_idx` (`cartID` ASC) VISIBLE,
  INDEX `fk_bookID_idx` (`bookID` ASC) VISIBLE,
  CONSTRAINT `fk_cartID`
    FOREIGN KEY (`cartID`)
    REFERENCES `Bookstore`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookID`
    FOREIGN KEY (`bookID`)
    REFERENCES `Bookstore`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`orderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`orderItems` (
  `idOrder_Product` INT NOT NULL,
  `orderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idOrder_Product`),
  INDEX `fk_orderID_idx` (`orderID` ASC) VISIBLE,
  INDEX `fk_productID_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_orderID`
    FOREIGN KEY (`orderID`)
    REFERENCES `Bookstore`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Bookstore`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstore`.`bookInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookstore`.`bookInventory` (
  `idbookInventory` INT NOT NULL,
  `bookID` INT NOT NULL,
  `bookStatus` VARCHAR(15) NULL,
  `buyingPrice` INT(10) NULL,
  `sellingPrice` INT(10) NULL,
  `quantity` INT(5) NULL,
  PRIMARY KEY (`idbookInventory`),
  INDEX `fk_bookID_idx` (`bookID` ASC) VISIBLE,
  CONSTRAINT `fk_bookID`
    FOREIGN KEY (`bookID`)
    REFERENCES `Bookstore`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
