-- MySQL Script generated by MySQL Workbench
-- Thu 16 Jul 2020 02:02:51 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Category` (
  `idCategory` INT NOT NULL,
  `category` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`books` (
  `ISBN` INT NOT NULL,
  `author` VARCHAR(30) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `cover` VARCHAR(30) NOT NULL,
  `edition` VARCHAR(5) NOT NULL,
  `publisher` VARCHAR(30) NOT NULL,
  `pubYear` INT(5) NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Category_idx` (`category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`userType` (
  `idUserType` INT NOT NULL,
  `userStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUserType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`users` (
  `userID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT(15) NULL,
  `userTypeID` INT NOT NULL,
  `Subscription` TINYINT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_userTypeID_idx` (`userTypeID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bookstore`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`address` (
  `idAddress` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `street` VARCHAR(30) NOT NULL,
  `street2` VARCHAR(30) NULL,
  `zipCode` INT(5) NOT NULL,
  `city` VARCHAR(15) NOT NULL,
  `state` VARCHAR(30) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `AddressType` VARCHAR(5) NULL,
  `userID` INT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_userID_idx` (`userID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`payment` (
  `cardNumber` INT NOT NULL,
  `name` VARCHAR(11) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `securityCode` INT(3) NOT NULL,
  `paymentType` VARCHAR(15) NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`cardNumber`),
  INDEX `fk_userID_idx` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`promotion` (
  `idPromotion` INT NOT NULL,
  `promoCode` VARCHAR(45) NOT NULL,
  `discountAmount` INT(5) NOT NULL,
  `startDate` DATE NOT NULL,
  `expirationDate` DATE NOT NULL,
  PRIMARY KEY (`idPromotion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`order` (
  `orderID` INT NOT NULL,
  `userID` INT NOT NULL,
  `total` INT NULL,
  `OrderDateTime` DATE NOT NULL,
  `AddressID` INT NOT NULL,
  `PromoID` INT NOT NULL,
  `paymentID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_UserID_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_addressID_idx` (`AddressID` ASC) VISIBLE,
  INDEX `fk_PromoID_idx` (`PromoID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`cart` (
  `idCart` INT NOT NULL,
  `userID` INT NOT NULL,
  `orderID` INT NOT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `fk_userID_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_orderID_idx` (`orderID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`cartItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`cartItems` (
  `idcartItems` INT NOT NULL,
  `cartID` INT NOT NULL,
  `bookID` INT NOT NULL,
  `quantity` INT(10) NOT NULL,
  PRIMARY KEY (`idcartItems`),
  INDEX `fk_cartID_idx` (`cartID` ASC) VISIBLE,
  INDEX `fk_bookID_idx` (`bookID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`orderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`orderItems` (
  `idOrder_Product` INT NOT NULL,
  `orderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idOrder_Product`),
  INDEX `fk_orderID_idx` (`orderID` ASC) VISIBLE,
  INDEX `fk_productID_idx` (`ProductID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`bookInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`bookInventory` (
  `idbookInventory` INT NOT NULL,
  `bookID` INT NOT NULL,
  `bookStatus` VARCHAR(15) NULL,
  `buyingPrice` INT(10) NULL,
  `sellingPrice` INT(10) NULL,
  `quantity` INT(5) NULL,
  PRIMARY KEY (`idbookInventory`),
  INDEX `fk_bookID_idx` (`bookID` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bookstore`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookstore`;
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (1, 'ActionAdventure');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (2, 'ScienceFiction');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (3, 'Fantasy');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (4, 'Romance');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (5, 'Suspense');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (6, 'Thriller');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (7, 'YoungAdult');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (8, 'Horror');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (9, 'Mystery');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (10, 'Historical');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (11, 'Education');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (12, 'GraphicNovel');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (13, 'Art');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (14, 'SelfHelp');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (15, 'Health');
INSERT INTO `bookstore`.`Category` (`idCategory`, `category`) VALUES (16, 'Children');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bookstore`.`userType`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookstore`;
INSERT INTO `bookstore`.`userType` (`idUserType`, `userStatus`) VALUES (1, 'Customer');
INSERT INTO `bookstore`.`userType` (`idUserType`, `userStatus`) VALUES (2, 'Admin');

COMMIT;

